### ISSUE TITLE
Documentation issues with building the vault ami

### ISSUE THREAD

**Issue by RohitJones** [scarolan/vault-aws-cf#4]
Hi, Thank you for making this template and providing the instructions to use it.
I encountered 2 issues when deploying the stack that are easily fixed but would be great if documented. 

1. The key, cert and binaries must be placed in a directory called "install_files" on the s3 bucket before building the ami
2. The names of the key and cert files (privkey.pem and fullchain.pem) cannot be renamed as the vault config generated on the vault servers does not respect the filenames in the vault.json packer template

Once, these two issues were fixed, I was able to deploy the stack successfully

**Comment by scarolan** [comment]
Thanks, would you mind submitting a pull request with your two fixes?  Thanks.

**Comment by evanniedojadlo** [comment]
I'm new to packer and seeing the following error which is likely related:

`Build 'amazon-ebs' errored after 5 seconds 898 milliseconds: Couldn't find specified instance profile: NoSuchEntity: Instance Profile Packer-S3-Access cannot be found.
	status code: 404, request id: 8c62db59-fdaa-4150-bd43-883415839ce6

==> Wait completed after 5 seconds 898 milliseconds

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Couldn't find specified instance profile: NoSuchEntity: Instance Profile Packer-S3-Access cannot be found.`

I am attempting to build the vault.json by using:

`packer build \                                                                                                                         ─╯
    -var 'aws_access_key=<enter-key-here>' \
    -var 'aws_secret_key=<enter-key-here>' \
    vault.json`

It looks like I am missing some arguments for s3? If anyone can assist I can create a PR on the readme and prevent anyone packer novices from running into this too :D

**Comment by evanniedojadlo** [comment]
The first error I resolved, this was just a permissions error within AWS IAM due to the packer template instance profile requirements. 

I am trying to figure out the S3 issue as mentioned above now as I returned the following errors from the vault.json packer template:

`==> amazon-ebs: warning: /var/cache/yum/x86_64/7/base/packages/unzip-6.0-21.el7.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY`

`==> amazon-ebs: warning: /var/cache/yum/x86_64/7/epel/packages/python2-pip-8.1.2-12.el7.noarch.rpm: Header V3 RSA/SHA256 Signature, key ID 352c64e5: NOKEY`

`==> amazon-ebs: 2020-09-09 20:06:15 [INFO] [install-consul.sh:get_consul_binary] s3://fto-shared-assets/install_files/consul_1.6.3_linux_amd64.zip  /tmp/install/consul.zip
==> amazon-ebs: fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden
==> amazon-ebs: 2020-09-09 20:06:16 [INFO] [install-consul.sh:get_consul_binary] s3 copy exit code == 1
==> amazon-ebs: 2020-09-09 20:06:16 [ERROR] [install-consul.sh:get_consul_binary] The copy of the consul binary from fto-shared-assets/consul_1.6.3_linux_amd64.zip failed`

`==> amazon-ebs: You are using pip version 8.1.2, however version 20.2.3 is available.
==> amazon-ebs: You should consider upgrading via the 'pip install --upgrade pip' command.
==> amazon-ebs: 2020-09-09 20:06:32 [INFO] [install-vault.sh:create_vault_user] User vault already exists. Will not create again.
==> amazon-ebs: 2020-09-09 20:06:32 [INFO] [install-vault.sh:get_vault_binary] Copying vault binary from fto-shared-assets to local
==> amazon-ebs: 2020-09-09 20:06:32 [INFO] [install-vault.sh:get_vault_binary] s3://fto-shared-assets/install_files/vault_1.3.2_linux_amd64.zip  /tmp/install/vault.zip
==> amazon-ebs: fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden
==> amazon-ebs: 2020-09-09 20:06:33 [ERROR] [install-vault.sh:get_vault_binary] The copy of the vault binary from fto-shared-assets/vault_1.3.2_linux_amd64.zip failed`

The errors appear to be what was mentioned above.

**Comment by RohitJones** [comment]
@evanniedojadlo You will need to modify the `vault.json` and the `consul.json` files before building the ami using packer.
At a bare minimum, you will need to change the `install_bucket`. The default s3 bucket belongs to the repo owner and is private which is why you are seeing the forbidden errors.

You will need to prepare your own bucket and place the vault and consul binaries (which you can get from the hashicorp website)  and your SSL key / certs in the bucket. 

On the topic of the original issue, you need to place the binaries and the key in a subdirectory called `install_files` in your bucket and your key and cert must be named privkey.pem and fullchain.pem respectively.

You might also have to change the `source_ami` value based on which aws region that you are deploying to.

Hope that this helps !

**Comment by evanniedojadlo** [comment]
@RohitJones thank you so much, this does help. When you're referring to "SSL key / certs in the bucket" which SSL key/certs, the IAM access key and secret access key?

**Comment by RohitJones** [comment]
no you need either a [self-signed certificate](https://devcenter.heroku.com/articles/ssl-certificate-self) or one from CA like [Let's encrypt](https://letsencrypt.org/getting-started/)

**Comment by evanniedojadlo** [comment]
@RohitJones I reached out to AWS regarding managed certs but otherwise generated the server.csr, server.key, and server.crt via the link you shared. Which of these do I rename to privkey.pem and fullchain.pem? 

I am also googling this so that I understand it, haven't done much with x509. Thanks again.

**Comment by evanniedojadlo** [comment]
I was able to convert the keys using the following:

`mv server.key privkey.pem
mv server.crt fullchain.pem`

Otherwise, it seems the cloudformation template is getting stuck at:

`
VaultCert  - CREATE_IN_PROGRESS

`

Which I will be able to troubleshoot. Otherwise, I will backtrack all of the issues I ran into and document them with a PR to help anyone new to packer, etc.

**Comment by RohitJones** [comment]
@evanniedojadlo yes, renaming server.key to privkey.pem and server.crt to fullchain.pem is correct. I've had success deploying the CF template by doing that.
One of the earlier issues I was facing is when I had named the files something else and had also accordingly adjusted the vault.json and consul.json files, but after deployment, the vault was still expecting the files to be named as privkey.pem and fullchain.pem

**Comment by scarolan** [comment]
This repo is super out of date - please consult with the hashi folks on more modern code for deploying vault on AWS.
