### ISSUE TITLE
Creating a snapshot

### ISSUE THREAD

**Issue by usernamemikem** [scarolan/vault-aws-cf#6]
Hi,

Thanks for the template, this set up works well and it's fast.  I'm trying to figure out how to run a manual snapshot.  When logged in with root token I ran the following command:

vault operator raft  list-peers

I get: No raft cluster configuration found

Is further configuration needed?  Can I use the consul-storage executable to create the snapshot?

Thanks.

Mike

**Comment by evanniedojadlo** [comment]
Hi, my understanding is that this template uses consul as a storage backend. You will need to review and run the consul snapshot here: [consul snapshot](https://www.consul.io/commands/snapshot) you will eventually want to automate this process or at least be realistic when it comes to production requirements. 

References to check out:
[storage backends](https://www.vaultproject.io/docs/configuration/storage)

I believe that there are some templates floating around that use raft, if not, I might have one to share.

**Comment by evanniedojadlo** [comment]
I would also advise updating those vault and consul binaries to the latest releases to make your life easier regarding upgrades. If you're unsure on how to do that let me know and I can point you in the right direction.

**Comment by usernamemikem** [comment]
Everything is generated via the template.  What token would I use to log into the consul?

Thanks.

Mike

**Comment by usernamemikem** [comment]
How do I retrieve the Consul token?  It looks like it's in AWS Secret Manager but I get "Failed to fetch secret' when I have full admin access?

Thanks.

Mike

**Comment by usernamemikem** [comment]
The is was opening the permissions in KMS.  The error was explicit using cli vs the console.

Have you ever successfully performed a consul operator raft save?  What is the syntax?

I can run consul members but I can run consul operator raft list-peers

Error getting peers: Failed to retrieve raft configuration: Unexpected response code: 403 (rpc error making call: Permission denied)

Can't find one working example.  Please show syntax necessary to back up your installation.

Thanks.

Mike

**Comment by evanniedojadlo** [comment]
regarding consul, you can ssh into the instances and create a consul ACL and token from that. from there, you can create snapshots via the CLI: https://learn.hashicorp.com/tutorials/consul/access-control-setup-production

I can double-check tomorrow (it's late here) on whether this template includes automation for setting up consul but based on what I remember I had to set some things up myself. Since this template uses consul as a backend storage, my understanding is that you need to use consul snapshots: https://www.consul.io/commands/snapshot

I have not personally used Consul Operator Raft but I will review that in the morning.

The permission denied responses are likely because you haven't created a consul ACL https://learn.hashicorp.com/tutorials/consul/access-control-setup-production

**Comment by usernamemikem** [comment]
Hi,

I was able to make a snapshot after I set the token to the bootstrap token.  I was able to restore it onto our development cluster but, of course there is a but, all the dev machines are now logging ACL not found errors.  The dev cluster is down.

So close.  I'll keep digging.

Thanks for all your help.

Mike

**Comment by usernamemikem** [comment]
Got it!

Since it's a copy of Prod, I had to copy the Prod tokens to the Dev machines.

I had to change the Unseal key to point to the Production Key using the arn and grant the Dev Role access to the key.

It brought all the settings over so I was able to login with my AD account.  All data is there!

Have a great weekend!

Mike

**Comment by evanniedojadlo** [comment]
good to hear, if you run into any issues feel free to open a request here: https://github.com/evanniedojadlo/vault-aws-cf I am going to begin maintaining this project within that repo.
